@TranslatorApi_HostAddress = http://localhost:5100

POST {{TranslatorApi_HostAddress}}/api/translate
Content-Type: application/json

{
  "htmlContent": "<h1>Hello World</h1><p>This is a <strong>test</strong>.</p>",
  "sourceLanguage": "en",
  "targetLanguages": ["pt", "fr"]
}

###

GET {{TranslatorApi_HostAddress}}/api/history
Accept: application/json

###
